// AI Steam - 常量配置

export const COLORS = {
  primary: '#3370FF',      // 飞书蓝
  primaryLight: '#598DFF',
  background: '#F5F6F7',
  surface: '#FFFFFF',
  text: '#1F2129',
  textSecondary: '#86909C',
  border: '#E5E6EB',
  success: '#00B42A',
  warning: '#F7BA1E',
  error: '#F53F3F',
  star: '#FFB224',
};

export const CATEGORIES = [
  { id: 'all', name: '全部', emoji: '🔥' },
  { id: 'image generation', name: '图像生成', emoji: '🎨' },
  { id: 'text processing', name: '文本处理', emoji: '📝' },
  { id: 'voice synthesis', name: '语音合成', emoji: '🎤' },
  { id: 'code assistant', name: '代码助手', emoji: '💻' },
  { id: 'video generation', name: '视频生成', emoji: '🎬' },
  { id: 'audio processing', name: '音频处理', emoji: '🎵' },
  { id: 'productivity', name: '效率工具', emoji: '⚡' },
  { id: 'entertainment', name: '娱乐', emoji: '🎮' },
];

export const MOCK_APPS = [
  {
    id: '1',
    name: 'AI 绘图大师',
    description: '强大的 AI 图像生成工具，支持多种风格',
    category: 'image generation' as const,
    icon: '🎨',
    screenshots: [],
    developer: 'AI Studio',
    version: '1.0.0',
    downloads: 125000,
    rating: 4.8,
    reviews: 3200,
    isFree: true,
    features: ['文生图', '图生图', '多种风格'],
    tags: ['AI', '绘画', '图像'],
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    id: '2',
    name: '智能写作助手',
    description: 'AI 驱动的写作辅助工具，提升写作效率',
    category: 'text processing' as const,
    icon: '✍️',
    screenshots: [],
    developer: 'WordAI',
    version: '2.1.0',
    downloads: 89000,
    rating: 4.6,
    reviews: 2100,
    isFree: true,
    features: ['智能补全', '语法检查', '风格优化'],
    tags: ['写作', '效率', 'AI'],
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    id: '3',
    name: '代码小助手',
    description: '智能代码补全和错误检测工具',
    category: 'code assistant' as const,
    icon: '🤖',
    screenshots: [],
    developer: 'DevTools',
    version: '1.5.0',
    downloads: 56000,
    rating: 4.9,
    reviews: 1800,
    isFree: true,
    features: ['代码补全', '错误检测', '代码解释'],
    tags: ['编程', 'AI', '开发工具'],
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    id: '4',
    name: 'AI 语音合成',
    description: '自然流畅的 AI 语音生成服务',
    category: 'voice synthesis' as const,
    icon: '🔊',
    screenshots: [],
    developer: 'VoiceAI',
    version: '1.2.0',
    downloads: 43000,
    rating: 4.5,
    reviews: 980,
    isFree: true,
    features: ['多音色', '情感合成', '多语言'],
    tags: ['语音', 'TTS', 'AI'],
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    id: '5',
    name: '视频生成器',
    description: '输入文案即可生成 AI 视频',
    category: 'video generation' as const,
    icon: '🎬',
    screenshots: [],
    developer: 'VideoAI',
    version: '1.0.0',
    downloads: 28000,
    rating: 4.3,
    reviews: 650,
    isFree: false,
    price: 9.9,
    features: ['文生视频', '模板丰富', '高清输出'],
    tags: ['视频', 'AI', '创作'],
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
];
